### ISSUE TITLE
[Questions] Help automating with GitHub Actions

### ISSUE THREAD

**Issue by hillelcoren** [Merrit/flutter_flatpak_example#9]
Hi,

Thanks for creating this project, it's been very useful! I've run into a few questions setting it up through GitHub Actions and was hoping you'd be able to help.

- How are you adding FlutterApp-Linux-Portable.tar.gz to the release, are you manually downloading it and then attaching it? If it's currently manual I assume we could use a upload-release-asset action to automate it?

- How do you suggest handling the flatpak.yml workflow file when using two repos. Should the entire action run on the code repo or would it make more sense to run the build-flatpak job on the flathub repo? What's unclear is I don't see how FlutterApp.flatpak is used in the action, or is it just to test manually? 

Hope you don't mind me creating an issue for questions. 

Cheers

**Comment by Merrit** [comment]
Hey, glad it has been helpful :)

> How are you adding FlutterApp-Linux-Portable.tar.gz to the release

For this example, manually.

> If it's currently manual I assume we could use a upload-release-asset action to automate it?

Exactly. You can see [here](https://github.com/Merrit/nyrna/blob/bc07a8138f337ab9e07909da7e03420eb7996fb0/.github/workflows/release.yml) where I upload artifacts for release on one of my apps, if you'd like a reference.

> What's unclear is I don't see how FlutterApp.flatpak is used in the action, or is it just to test manually?

Basically it is here for testing, so people can install it and see the app installs as a Flatpak and runs.

Essentially what I do is have my app's repo build, package, and release the portable version of the app. Afterwards a PR is made to the app's Flathub repo to update the `.yml` file with the new url & sha256 of the new app portable build, which triggers a test build, and accepting the PR triggers an update in Flathub. You can see one of my app's Flathub repos [here](https://github.com/flathub/codes.merritt.Nyrna) for reference.

I rarely bother doing anything with actual `.flatpak` files, mostly I update the Flathub repo, I can test the build that buldbot makes and push it live. :)

**Comment by hillelcoren** [comment]
Brilliant, thanks again!

**Comment by Merrit** [comment]
Glad I could help 💙 :)
